Client/Controllers/EmployeeController.cs
using API.Models;
using Client.Contract;
using Client.ViewModels.AccountRole;
using Client.ViewModels.Employee;
using Client.ViewModels.Role;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Client.Controllers;

public class EmployeeController : Controller
{
    private readonly IEmployeeRepository repository;
    private readonly IAccountRoleRepository _accountRoleRepository;
    private readonly IRoleRepository _roleRepository;
    private readonly IManagerRepository _managerRepository;

    public EmployeeController(IEmployeeRepository repository, IRoleRepository roleRepository, IManagerRepository managerRepository, IAccountRoleRepository accountRoleRepository)
    {
        this.repository = repository;
        _roleRepository = roleRepository;
        _managerRepository = managerRepository;
        _accountRoleRepository = accountRoleRepository;
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index()
    {
        var result = await repository.GetEmployees();
        var listEmployee = new List<EmployeeVM>();

        if (result.Data != null)
        {
            listEmployee = result.Data.ToList();
        }

        return View(listEmployee);
    }
    [Authorize(Roles = "Admin")]
    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var resultManager = await _managerRepository.Get();
        var listManagers = new List<ManagerVM>();

        if (resultManager.Data != null)
        {
            listManagers = resultManager.Data.ToList();
        }
        // add to view data
        ViewData["Managers"] = listManagers;
        return View();
    }
    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> Create(EmployeeVM newEmploye)
    {

        var result = await repository.Post(newEmploye);
        if (result.Code == 201)
        {
            TempData["Success"] = "Data berhasil masuk";
            return RedirectToAction(nameof(Index));
        }
        else
        {
            if (result.Errors?.Email?.Length > 0)
            {
                TempData["EmailError"] = $"Email: {result.Errors.Email[0]}";
            }

            // Check for PhoneNumber errors
            if (result.Errors?.PhoneNumber?.Length > 0)
            {
                TempData["PhoneError"] = $"Phone Number: {result.Errors.PhoneNumber[0]}";
            }

            return Redirect("~/employee/create");
        }
    }
    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> Delete(Guid guid)
    {
        try
        {
            var result = await repository.Delete(guid);

            if (result.Status == "200" && result.Data?.Guid != null)
            {
                var employee = new Employee
                {
                    Guid = result.Data.Guid
                };

                TempData["Success"] = "Data berhasil dihapus";
            }
            else
            {
                TempData["Error"] = "Gagal menghapus data";
            }
        }
        catch (Exception ex)
        {
            TempData["Error"] = "Terjadi kesalahan saat menghapus data: " + ex.Message;
        }

        return RedirectToAction(nameof(Index));
    }
    [Authorize(Roles = "Admin")]
    [HttpGet]
    public async Task<IActionResult> Edit(Guid guid)
    {
        var result = await repository.Get(guid);

        if (result.Data?.Guid is null)
        {
            return RedirectToAction(nameof(Index));
        }

        var employee = new EmployeeVM
        {
            Guid = result.Data.Guid,
            NIK = result.Data.NIK,
            FirstName = result.Data.FirstName,
            LastName = result.Data.LastName,
            Gender = result.Data.Gender,
            PhoneNumber = result.Data.PhoneNumber,
            EligibleLeave = result.Data.EligibleLeave,
            HiringDate = result.Data.HiringDate,
            ManagerGuid = result.Data.ManagerGuid,
            Email = result.Data.Email,
            Password = result.Data.Password,
            ConfirmPassword = result.Data.ConfirmPassword
        };

        var resultManager = await _managerRepository.Get();
        var listManagers = new List<ManagerVM>();

        if (resultManager.Data != null)
        {
            listManagers = resultManager.Data.ToList();
        }

        var resultRole = await _roleRepository.Get();
        var listRoles = new List<RoleVM>();

        if (resultRole.Data != null)
        {
            listRoles = resultRole.Data.ToList();
        }

		var resultAccountRole = await _accountRoleRepository.Get();
		var listAccountRole = new List<AccountRoleVM>();

		if (resultAccountRole.Data != null) listAccountRole = resultAccountRole.Data.ToList();

		var accountRoleEmployee = new AccountRoleVM();
        foreach (var accountRole in listAccountRole)
        {
            if (accountRole.AccountGuid == result.Data.Guid)
            {
                accountRoleEmployee = accountRole;
            }
        }
        // add to view data
        ViewData["Managers"] = listManagers;
        ViewData["AccountRole"] = accountRoleEmployee;
        ViewData["Roles"] = listRoles;

        return View(employee);
    }
    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> Edit(EmployeeVM employee)
    {
        var result = await repository.Put(employee.Guid, employee);
        if (result.Code == 200)
        {
            return RedirectToAction(nameof(Index));
        }
        else if (result.Status == "409")
        {
            ModelState.AddModelError(string.Empty, result.Message);
            return View();
        }

        return View();
    }

}

Client/Controllers/HistoryLeaveRequestController.cs
using API.Models;
using Client.Contract;
using Client.ViewModels.LeaveHistory;
using Client.ViewModels.LeaveRequest;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;

namespace Client.Controllers;

[Authorize]
public class HistoryLeaveRequestController : Controller

{
    private readonly IHistoryLeaveRequestRepository _history;

    public HistoryLeaveRequestController(IHistoryLeaveRequestRepository historyLeaveRequestRepository)
    {
        _history = historyLeaveRequestRepository;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        try
        {
            var result = await _history.GetLeaveHistory();
            var LeaveHistory = new List<HistoryVM>();

            if (result.Data != null)
            {
                LeaveHistory = result.Data.ToList();
            }
            return View(LeaveHistory);
        }
        catch (Exception ex)
        {
            return StatusCode(500, "Internal Server Error: " + ex.Message);
        }
    }

    [HttpGet]
    public async Task<IActionResult> Approve()
    {
        try
        {
            var result = await _history.GetLeaveHistoryApprove();
            var HistoryApprove = new List<HistoryVM>();

            if (result.Data != null)
            {
                HistoryApprove = result.Data.ToList();
            }
            return View(HistoryApprove);
        }
        catch (Exception ex)
        {
            return StatusCode(500, "Internal Server Error: " + ex.Message);
        }
    }

    [HttpGet]
    public async Task<IActionResult> Pending()
    {
        try
        {
            var result = await _history.GetLeaveHistoryPending();
            var HistoryPending = new List<HistoryVM>();

            if (result.Data != null)
            {
                HistoryPending = result.Data.ToList();
            }
            return View(HistoryPending);
        }
        catch (Exception ex)
        {
            return StatusCode(500, "Internal Server Error: " + ex.Message);
        }
    }

    [HttpGet]
    public async Task<IActionResult> Reject()
    {
        try
        {
            var result = await _history.GetLeaveHistoryReject();
            var istoryReject = new List<HistoryVM>();

            if (result.Data != null)
            {
                istoryReject = result.Data.ToList();
            }
            return View(istoryReject);
        }
        catch (Exception ex)
        {
            return StatusCode(500, "Internal Server Error: " + ex.Message);
        }
    }
    [Authorize(Roles = "User")]
    [HttpGet]
    public async Task<IActionResult> byNik()
    {
        try
        {
            var result = await _history.GetLeaveHistorybyNik();
            var istoryReject = new List<HistoryVM>();

            if (result.Data != null)
            {
                istoryReject = result.Data.ToList();
            }
            return View(istoryReject);
        }
        catch (Exception ex)
        {
            return StatusCode(500, "Internal Server Error: " + ex.Message);
        }
    }
    [Authorize(Roles = "Manager")]
    [HttpGet]
    public async Task<IActionResult> byManager()
    {
        try
        {
            var result = await _history.GetLeaveHistorybyManager();
            var nymanager = new List<HistoryVM>();

            if (result.Data != null)
            {
                nymanager = result.Data.ToList();
            }
            return View(nymanager);
        }
        catch (Exception ex)
        {
            return StatusCode(500, "Internal Server Error: " + ex.Message);
        }
    }
}

Client/Controllers/LeaveTypeController.cs
using API.DTOs.Employees;
using API.Models;
using Client.Contract;
using Client.ViewModels.LeaveType;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

public class LeaveTypeController : Controller
{
    private readonly ILeaveTypeRepository repository;

    public LeaveTypeController(ILeaveTypeRepository repository)
    {
        this.repository = repository;
    }
    [Authorize]
    public async Task<IActionResult> Index()
    {
        var result = await repository.Get();
        var ListLeaveType = new List<LeaveTypeVM>();

        if (result.Data != null)
        {
            ListLeaveType = result.Data.ToList();
        }
        return View(ListLeaveType);
    }
    [Authorize(Roles = "Admin")]
    [HttpGet]
    public IActionResult AddType()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddType(LeaveTypeVM leaveTypeVM)
    {
        var result = await repository.Post(leaveTypeVM);
        if (result.Status == "200")
        {
            TempData["Success"] = "Data berhasil masuk";
            return RedirectToAction(nameof(Index));
        }
        else if (result.Status == "404")
        {
            ModelState.AddModelError(string.Empty, result.Message);
            return View(leaveTypeVM); // Kembalikan tampilan View dengan data yang sudah diisi sebelumnya
        }
        return RedirectToAction(nameof(Index));
    }


    [HttpPost]
    public async Task<IActionResult> Delete(Guid guid)
    {
        try
        {
            var result = await repository.Delete(guid);

            if (result.Status == "200" && result.Data?.Guid != null)
            {
                var employee = new Employee
                {
                    Guid = result.Data.Guid
                };

                TempData["Success"] = "Data berhasil dihapus";
            }
            else
            {
                TempData["Error"] = "Gagal menghapus data";
            }
        }
        catch (Exception ex)
        {
            TempData["Error"] = "Terjadi kesalahan saat menghapus data: " + ex.Message;
        }

        return RedirectToAction(nameof(Index));
    }
    [Authorize(Roles = "Admin")]
    [HttpGet]
    public async Task<IActionResult> EditType(Guid guid)
    {
        var result = await repository.Get(guid);

        if (result.Data?.Guid is null)
        {
            return RedirectToAction(nameof(Index));
        }

        var leaveType = new LeaveTypeVM
        {
            Guid = result.Data.Guid,
            LeaveName = result.Data.LeaveName,
            LeaveDay = result.Data.LeaveDay,
            LeaveDescription = result.Data.LeaveDescription,

        };

        return View(leaveType);
    }

    [HttpPost]
    public async Task<IActionResult> EditType(LeaveTypeVM leaveType)
    {
        if (!ModelState.IsValid)
        {
            return View(leaveType);
        }
        var result = await repository.Put(leaveType.Guid, leaveType);

        if (result.Status == "200")
        {
            TempData["Success"] = "Data berhasil diubah";
        }
        else
        {
            TempData["Error"] = "Gagal menghapus data";
        }
        return RedirectToAction(nameof(Index));
    }
}

Client/Views/Shared/_Layout.cshtml
@{
    bool isAdmin = User.IsInRole("Admin");
    bool isUser = User.IsInRole("User");
    bool isManager = User.IsInRole("Manager");
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Mazer Admin Dashboard</title>

    <link rel="stylesheet" href="~/template/assets/css/main/app.css">
    <link rel="stylesheet" href="~/template/assets/css/main/app-dark.css">
    <link rel="shortcut icon" href="~/template/assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="~/template/assets/images/logo/favicon.png" type="image/png">
    <link rel="stylesheet" href="~/template/assets/css/shared/iconly.css">

</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header position-relative">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="logo">
                            <a href="index.html"><img src="~/img/logo.png" alt="Logo" srcset="" style="width: 150px; height: auto;"></a>
                        </div>
                        <div class="theme-toggle d-flex gap-2  align-items-center mt-2">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--system-uicons" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2" opacity=".3"></path><g transform="translate(-210 -1)"><path d="M220.5 2.5v2m6.5.5l-1.5 1.5"></path><circle cx="220.5" cy="11.5" r="4"></circle><path d="m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2"></path></g></g></svg>
                            <div class="form-check form-switch fs-6">
                                <input class="form-check-input  me-0" type="checkbox" id="toggle-dark">
                                <label class="form-check-label"></label>
                            </div>
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z"></path></svg>
                        </div>
                        <div class="sidebar-toggler  x">
                            <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title">Menu</li>

                        <li class="sidebar-item @(Context.Request.Path == "/Home/Index" ? "active" : "")">
                            <a href="@Url.Action("Index", "Home")" class='sidebar-link'>
                                <i class="bi bi-grid-fill"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>

                        @if (isAdmin)
                        {
                            <li class="sidebar-item @(Context.Request.Path == "/Employee/Index" ? "active" : "")">
                                <a href="@Url.Action("Index", "Employee")" class='sidebar-link'>
                                    <i class="bi bi-people-fill"></i>
                                    <span>Employee Management</span>
                                </a>
                            </li>
                        }

                        @if (isUser)
                        {
                            <li class="sidebar-item @(Context.Request.Path == "/LeaveRequest/Create" ? "active" : "")">
                                <a href="/LeaveRequest/Create" class='sidebar-link'>
                                    <i class="bi bi-file-earmark-medical-fill"></i>
                                    <span>Leave Request</span>
                                </a>
                            </li>
                        }

                        @if (isUser)
                        {
                            <li class="sidebar-item @(Context.Request.Path == "/LeaveRequest/GetByEmployee" ? "active" : "")">
                                <a href="@Url.Action("GetByEmployee", "LeaveRequest")" class='sidebar-link'>
                                    <i class="bi bi-file-earmark-spreadsheet-fill"></i>
                                    <span>Pending Request</span>
                                </a>
                            </li>
                        }

                        @if (isManager)
                        {
                            <li class="sidebar-item @(Context.Request.Path == "/LeaveRequest/GetByManager" ? "active" : "")">
                                <a href="@Url.Action("GetByManager", "LeaveRequest")" class='sidebar-link'>
                                    <i class="bi bi-file-earmark-medical-fill"></i>
                                    <span>Employee Leave Requests</span>
                                </a>
                            </li>
                        }

                        @if (isUser)
                        {
                            <li class="sidebar-item @(Context.Request.Path == "/HistoryLeaveRequest/ByNik" ? "active" : "")">
                                <a href="@Url.Action("ByNik", "HistoryLeaveRequest")" class='sidebar-link'>
                                    <i class="bi bi-file-earmark-spreadsheet-fill"></i>
                                    <span>Leave Request History</span>
                                </a>
                            </li>
                        }

                        @if (isManager)
                        {
                            <li class="sidebar-item @(Context.Request.Path == "/HistoryLeaveRequest/byManager" ? "active" : "")">
                                <a href="@Url.Action("byManager", "HistoryLeaveRequest")" class='sidebar-link'>
                                    <i class="bi bi-file-earmark-spreadsheet-fill"></i>
                                    <span>Employee Leave Request histories</span>
                                </a>
                            </li>
                        }

                        @if (isAdmin)
                        {

                            <li class="sidebar-item @(Context.Request.Path == "/LeaveType/Index" ? "active" : "")">
                                <a href="@Url.Action("Index", "LeaveType")" class='sidebar-link'>
                                    <i class="bi bi-file-earmark-spreadsheet-fill"></i>
                                    <span>Leave Type Management</span>
                                </a>
                            </li>
                        }

                        <li class="sidebar-item @(Context.Request.Path == "/Account/Logout" ? "active" : "")">
                            <a href="@Url.Action("Logout", "Account")" class='sidebar-link'>
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Logout</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block d-xl-none">
                    <i class="bi bi-justify fs-3"></i>
                </a>
            </header>

            <div class="page-heading">
                <h3>Dashboard</h3>
            </div>
            <div class="page-content">
                @RenderBody()
            </div>
            
           
        </div>
    </div>
    <script src="~/template/assets/js/bootstrap.js"></script>
    <script src="~/template/assets/js/app.js"></script>

    <!-- Need: Apexcharts -->
    <script src="~/template/assets/extensions/apexcharts/apexcharts.min.js"></script>
    <script src="~/template/assets/js/pages/dashboard.js"></script>
    <script src="~/template/assets/extensions/simple-datatables/umd/simple-datatables.js"></script>
    <script src="~/template/assets/js/pages/simple-datatables.js"></script>

</body>

</html>

Client/Views/Shared/_LayoutLogin.cshtml
@{
    var failMessage = TempData["LoginError"] as string;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Mazer Admin Dashboard</title>
    <link rel="stylesheet" href="~/template/assets/css/main/app.css">
    <link rel="stylesheet" href="~/template/assets/css/pages/auth.css">
    <link rel="shortcut icon" href="~/template/assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="~/template/assets/images/logo/favicon.png" type="image/png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
</head>

<body>
    <div id="auth">

        <div class="row h-100">
            <div class="col-lg-5 col-12">
                <div id="auth-left">
                    <div class="logo ">
                        <a href="index.html"><img src="~/img/logo.png" alt="Logo" srcset="" style="width: 400px; height: auto;"></a>
                    </div>
                @RenderBody()   
                </div>
            </div>
            <div class="col-lg-7 d-none d-lg-block">
                <div id="auth-right">
                </div>
            </div>
        </div>

    </div>
    @await RenderSectionAsync("Scripts", required: false)
    @if (!string.IsNullOrEmpty(failMessage))
    {
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function () {
                toastr.options = {
                    "positionClass": "toast-top-left",
                    "closeButton": true,
                    "progressBar": true,
                    "timeOut": 3000
                };
                toastr.error('@failMessage');
            });
        </script>
    }

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
</body>
</html>